services:

  gbot-7.0-prod:
    container_name: "GBot_7.0_prod"
    image: ghcr.io/cgoulart35/gbot:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    env_file: ./Shared/gbot.env
    volumes:
      - ./Shared/serviceAccountKey.json:/GBot/Shared/serviceAccountKey.json
    restart: unless-stopped
    init: true
    ports:
      - 5004:5004
