version: "3.8"
services:

  gbot-4.0-dev:
    container_name: "GBot_4.0_dev"
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    env_file: ./Shared/gbot.env
    volumes:
      - ./Shared/serviceAccountKey.json:/GBot/Shared/serviceAccountKey.json
    restart: unless-stopped
    ports:
      - 5678:5678
      - 5004:5004