# command names
BET_NAME = "bet"
BUY_NAME = "buy"
CONFIG_NAME = "config"
CHANNEL_NAME = "channel"
CRAFT_NAME = "craft"
DESTROY_NAME = "destroy"
DIS_NAME = "dis"
ELEVATOR_NAME = "elevator"
GUESS_NAME = "guess"
HALO_NAME = "name"
HISTORY_NAME = "history"
HYPE_NAME = "hype"
ITEM_NAME = "item"
ITEMS_NAME = "items"
LEAVEDIS_NAME = "leavedis"
MARKET_NAME = "market"
PATREON_NAME = "patreon"
PAUSE_NAME = "pause"
PLAY_NAME = "play"
PREFIX_NAME = "prefix"
QUEUE_NAME = "queue"
REACT_NAME = "react"
RENAME_NAME = "rename"
REPORT_NAME = "report"
RESUME_NAME = "resume"
ROLE_NAME = "role"
SELL_NAME = "sell"
SEND_NAME = "send"
SKIP_NAME = "skip"
SPOTIFY_NAME = "spotify"
STOP_NAME = "stop"
TOGGLE_NAME = "toggle"
UMBRELLA_NAME = "umbrella"
UNMATCH_NAME = "unmatch"
WALLET_NAME = "wallet"
WALLETS_NAME = "wallets"
WHODIS_NAME = "whodis"

# command briefs
BET_BRIEF = "Make a guess. If you win, you earn the amount of points bet. If you lose, you lose those points."
BUY_BRIEF = "Buy another user's item for sale in the discord server."
CONFIG_BRIEF = "Shows the server's current GBot configuration. (admin only)"
CHANNEL_BRIEF = "Set the channel for a specific GBot feature in this server. (admin only)"
CRAFT_BRIEF = "Craft items to show off and trade."
DESTROY_BRIEF = "Destroy an item in your inventory."
DIS_BRIEF = "Guess the name of the user you are paired with for a chance to win GCoin."
ELEVATOR_BRIEF = "Toggle elevator mode to keep the last played sound on repeat."
GUESS_BRIEF = "Make a guess with a winning reward of 1.00 GCoin."
HALO_BRIEF = "Participate in or leave the weekly GBot Halo competition. (admin optional)"
HISTORY_BRIEF = "Show your transaction history, or a user's transaction history in this server. (admin optional)"
HYPE_BRIEF = "Set a regex to match against messages, and a list of possible responses to reply with. (admin only)"
ITEM_BRIEF = "Show off an item in your inventory."
ITEMS_BRIEF = "List all items in your inventory, or another user's inventory in this server."
LEAVEDIS_BRIEF = "Remove the server's 'Who Dis?' role opting you out of any future games."
MARKET_BRIEF = "Show all market items for sale and personal trade requests in the discord server."
PATREON_BRIEF = "In the GBot Patreon server, specify your server's ID to enable GBot functionality. (patrons only)"
PAUSE_BRIEF = "Pauses the current sound being played."
PLAY_BRIEF = "Play videos/music downloaded from YouTube."
PREFIX_BRIEF = "Set the prefix for all GBot commands used in this server. (admin only)"
QUEUE_BRIEF = "Displays the current sounds in queue."
REACT_BRIEF = "Set a regex to match against messages, and a list of possible emojis to react with. (admin only)"
RENAME_BRIEF = "Rename an item in your inventory."
REPORT_BRIEF = "Report a user to server admins for bad behavior."
RESUME_BRIEF = "Resumes the current sound being played."
ROLE_BRIEF = "Set the role for a specific GBot feature in this server. (admin only)"
SELL_BRIEF = "Sell an item to another user in this discord server."
SEND_BRIEF = "Send GCoin to another user in this server."
SKIP_BRIEF = "Skips the current sound being played."
SPOTIFY_BRIEF = "Play current spotify activity downloaded from YouTube."
STOP_BRIEF = "Stops the bot from playing sounds and clears the queue."
TOGGLE_BRIEF = "Turn on/off all functionality for a GBot feature in this server. (admin only)"
UMBRELLA_BRIEF = "Start the incoming Storm and earn 0.25 GCoin."
UNMATCH_BRIEF = "Remove an existing regular expression match response in this server. (admin only)"
WALLET_BRIEF = "Show your wallet, or another user's wallet in this server."
WALLETS_BRIEF = "Show wallets of all users in this server."
WHODIS_BRIEF = "Start or end a mini-game where you try to guess a random user in the server you are paired with."

# command descriptions
BET_DESCRIPTION = "Make a guess. If you win, you earn the amount of points bet within your wallet. If you lose, you lose those points. Multiplier applied for guesses made in 4 attempts or less."
BUY_DESCRIPTION = "Buy another user's item for sale in the discord server. Create a request to buy from a user, complete a user's pending sell request, or buy an item for sale in the server's market."
CONFIG_DESCRIPTION = "Shows the server's current GBot configuration. (admin only)"
CHANNEL_DESCRIPTION = "Set the channel for a specific GBot feature in this server. (admin only)\nchannel_type options are: admin, storms"
CRAFT_DESCRIPTION = "Craft items to show off and trade. Surround name with double quotes if multiple words.\ntype options are: image"
DESTROY_DESCRIPTION = "Destroy an item in your inventory."
DIS_DESCRIPTION = "Guess the name of the user you are paired with for a chance to win GCoin."
ELEVATOR_DESCRIPTION = "Toggle elevator mode to keep the last played sound on repeat."
GUESS_DESCRIPTION = "Make a guess with a winning reward of 1.00 GCoin. Multiplier applied for guesses made in 4 attempts or less."
HALO_DESCRIPTION = "Participate in or leave the weekly GBot Halo competition. (admin optional)\naction options are: <gamertag>, rm"
HISTORY_DESCRIPTION = "Show your transaction history, or another user's transaction history in this server. Admin role needed to show other user's history. (admin optional)"
HYPE_DESCRIPTION = "Set a regular expression to match against new messages in this server, and a list of possible responses to reply to it with. Surround regex and response each with double quotes if multiple words. (admin only)"
ITEM_DESCRIPTION = "Show off an item in your inventory."
ITEMS_DESCRIPTION = "List all items in your inventory, or another user's inventory in this server."
LEAVEDIS_DESCRIPTION = "Remove the server's 'Who Dis?' role opting you out of any future games."
MARKET_DESCRIPTION = "Show all market items for sale and personal trade requests in the discord server."
PATREON_DESCRIPTION = "In the GBot Patreon server, specify a server's ID to enable GBot functionality in that server. (patrons only)"
PAUSE_DESCRIPTION = "Pauses the current sound being played."
PLAY_DESCRIPTION = "Play videos/music downloaded from YouTube. No playlists or livestreams."
PREFIX_DESCRIPTION = "Set the prefix for all GBot commands used in this server. (admin only)"
QUEUE_DESCRIPTION = "Displays the current sounds in queue."
REACT_DESCRIPTION = "Set a regular expression to match against new messages in this server, and a list of possible emojis to react to it with. Surround regex with double quotes if multiple words. (admin only)"
RENAME_DESCRIPTION = "Rename an item in your inventory."
REPORT_DESCRIPTION = "Report a user to server admins for bad behavior. The reported user's last 5 messages will be captured from the channel sent in, or an ongoing Who Dis game."
RESUME_DESCRIPTION = "Resumes the current sound being played."
ROLE_DESCRIPTION = "Set the role for a specific GBot feature in this server. (admin only)\nrole_type options are: admin, whodis"
SELL_DESCRIPTION = "Sell an item to another user in this discord server. Create a request to sell to a user, complete a user's pending buy request, or place an item for sale in the server's market."
SEND_DESCRIPTION = "Send GCoin to another user in this server."
SKIP_DESCRIPTION = "Skips the current sound being played."
SPOTIFY_DESCRIPTION = "Play current spotify activity downloaded from YouTube. Songs are added to the queue as the user's activity changes."
STOP_DESCRIPTION = "Stops the bot from playing sounds and clears the queue."
TOGGLE_DESCRIPTION = "Turn on/off all functionality for a GBot feature in this server. (admin only)\nfeature_type options are: gcoin, gtrade, hype, music, storms, whodis, legacy prefix commands"
UMBRELLA_DESCRIPTION = "Start the incoming Storm and earn 0.25 GCoin."
UNMATCH_DESCRIPTION = "Remove an existing regular expression match response in this server. (admin only)"
WALLET_DESCRIPTION = "Show your wallet, or another user's wallet in this server."
WALLETS_DESCRIPTION = "Show wallets of all users in this server."
WHODIS_DESCRIPTION = "Start or end a mini-game where you try to guess a random user in the server you are paired with. You have 1 guess, and if you guess correctly you earn GCoin. You can play once every hour."

# command argument descriptions
BET_GCOIN_DESCRIPTION = "The amount of GCoin you want to bet on your guess."
BET_NUMBER_DESCRIPTION = "The number you want to guess."
BUY_ITEM_DESCRIPTION = "The item you want to buy."
BUY_USER_DESCRIPTION = "The user you want to buy the item from."
CHANNEL_CHANNEL_DESCRIPTION = "A channel in the server."
CHANNEL_TYPE_DESCRIPTION = "The type of channel to configure."
CRAFT_NAME_DESCRIPTION = "The name of the item you want to craft."
CRAFT_TYPE_DESCRIPTION = "The type of item you want to craft."
CRAFT_VALUE_DESCRIPTION = "The amount of GCoin you want to spend on crafting."
DESTROY_ITEM_DESCRIPTION = "The name of the item you want to destroy."
DIS_USER_DESCRIPTION = "The user you think you are paired with."
GUESS_NUMBER_DESCRIPTION = "The number you want to guess."
HISTORY_USER_DESCRIPTION = "The user whose transaction history you want to see."
HYPE_REGEX_DESCRIPTION = "A regular expression used for automated replies."
HYPE_RESPONSES_DESCRIPTION = "A double-quote separated list of possible replies for the given regex."
ITEM_ITEM_DESCRIPTION = "The item you want to show off."
ITEMS_USER_DESCRIPTION = "The user whose inventory you want to see."
PATREON_SERVER_ID_DESCRIPTION = "The ID of the server you are registering GBot with."
PLAY_INPUT_DESCRIPTION = "A song or video name, or a YouTube video URL."
PREFIX_PREFIX_DESCRIPTION = "The character(s) used for this server's command prefix."
REACT_EMOJIS_DESCRIPTION = "A list of possible reaction emojis for the given regex."
REACT_REGEX_DESCRIPTION = "A regular expression used for automated reactions."
RENAME_ITEM_DESCRIPTION = "The name of the item you want to rename."
RENAME_NAME_DESCRIPTION = "The new name of the item."
REPORT_USER_DESCRIPTION = "The user you want to report for bad behavior (leave blank for Who Dis)."
ROLE_ROLE_DESCRIPTION = "A role in the server."
ROLE_TYPE_DESCRIPTION = "The type of role to configure."
SELL_ITEM_DESCRIPTION = "The item you want to sell."
SELL_USER_DESCRIPTION = "The user you want to sell the item to."
SEND_AMOUNT_DESCRIPTION = "The amount of GCoin to send."
SEND_USER_DESCRIPTION = "The user to send GCoin to."
SPOTIFY_USER_DESCRIPTION = "The user whose Spotify activity you want to listen to."
TOGGLE_FEATURE_TYPE_DESCRIPTION = "The feature to toggle on/off."
WALLET_USER_DESCRIPTION = "The user whose wallet you want to view."

# command aliases
BET_ALIASES = ['b']
BUY_ALIASES = ['by']
CONFIG_ALIASES = ['c']
CHANNEL_ALIASES = ['ch']
CRAFT_ALIASES = ['cr']
DESTROY_ALIASES = ['d']
DIS_ALIASES = ['ds']
ELEVATOR_ALIASES = ['e']
GUESS_ALIASES = ['g']
HALO_ALIASES = ['h']
HISTORY_ALIASES = ['hs']
HYPE_ALIASES = ['hy']
ITEM_ALIASES = ['i']
ITEMS_ALIASES = ['is']
LEAVEDIS_ALIASES = ['ld']
MARKET_ALIASES = ['m']
PATREON_ALIASES = ['pt']
PAUSE_ALIASES = ['ps']
PLAY_ALIASES = ['p']
PREFIX_ALIASES = ['pr']
QUEUE_ALIASES = ['q']
REACT_ALIASES = ['re']
RENAME_ALIASES = ['rn']
REPORT_ALIASES = ['rp']
RESUME_ALIASES = ['r']
ROLE_ALIASES = ['rl']
SELL_ALIASES = ['sl']
SEND_ALIASES = ['sd']
SKIP_ALIASES = ['s']
SPOTIFY_ALIASES = ['sp']
STOP_ALIASES = ['st']
TOGGLE_ALIASES = ['t']
UMBRELLA_ALIASES = ['u']
UNMATCH_ALIASES = ['um']
WALLET_ALIASES = ['w']
WALLETS_ALIASES = ['ws']
WHODIS_ALIASES = ['wd']